baseURL: https://blog.jracaud.com
locale: en-us
defaultContentLanguage: en
title: JRacaud
theme: jracaud
# googleAnalytics: UA-123456789-1
# disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  jpeg:
    quality: 99
  webp:
    quality: 99
  avif:
    quality: 99

params:
  description: Software developer that experiment with stuffs.
  homeMetaContent: Software developer that experiment with stuffs.
  footer: 2026 JRacaud.
  dateFormat: 2 Jan 2006
  katex: true
  hideHeaderLinks: false
  defaultDarkTheme: false
  logoAlt: JRacaud

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Articles
      url: /articles/
      weight: 2
    - name: Snippets
      url: /snippets/
      weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 0
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 2
  tableOfContents:
    endLevel: 6
    startLevel: 1
